name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - uses: php-actions/composer@v5
        with: lint

      - uses: php-actions/composer@v5
        with: test
