name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          version: 1

      - name: Lint
        run: composer lint
      
      - name: Test
        run: composer test
